services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    user: root
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - double-ii
  backend:
    image: public.ecr.aws/sam/build-nodejs18.x
    command: sh -c "sam build && sam local start-api --container-host host.docker.internal --docker-network double-ii --host 0.0.0.0 --debug --warm-containers EAGER"
    working_dir: ${PWD}/backend
    volumes:
      - ./backend:${PWD}/backend
      - ./backend/config/aws:/root/.aws
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - double-ii

volumes:
  dynamodb_data:

networks:
  double-ii:
    name: double-ii
    driver: bridge
