services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    user: root
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - double-ii
  backend:
    build:
      context: backend/app
      dockerfile: Dockerfile
    command: sh -c "npm install && node src/app.js"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    ports:
      - "3000:8080"
    volumes:
      - ./backend/config/aws:/root/.aws
      - ./backend/app:/var/task
    networks:
      - double-ii
  frontend:
    image: node:20
    command: sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    working_dir: /app
    networks:
      - double-ii
  
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8000:8080"
    volumes:
      - ./backend/config/appointment-api-schema.yml:/tmp/swagger.yml
    environment:
      - SWAGGER_JSON=/tmp/swagger.yml

volumes:
  dynamodb_data:

networks:
  double-ii:
    name: double-ii
    driver: bridge
