services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    user: root
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - double-ii
  backend:
    build:
      context: backend/app
      dockerfile: Dockerfile
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    ports:
      - "3000:8080"
    volumes:
      - ./backend/config/aws:/root/.aws
    networks:
      - double-ii

volumes:
  dynamodb_data:

networks:
  double-ii:
    name: double-ii
    driver: bridge
