AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Parameters:
  StageName:
    Type: String
    Description: "The name of the stage (e.g., dev, prod)"
    Default: "v1"
  BedrockAgentIdUnregisteredUser:
    Type: String
    Description: "id of the bedrock agent"
  BedrockAgentAliasUnregisteredUser:
    Type: String
    Description: "alias id of the bedrock agent"
  BedrockAgentIdRegisteredUser:
    Type: String
    Description: "id of the bedrock agent"
  BedrockAgentAliasRegisteredUser:
    Type: String
    Description: "alias id of the bedrock agent"
  SesArn:
    Type: String
    Description: "SES ARN"
  WebBaseUrl:
    Type: String
    Description: "Base URL of the web app"
  GoogleClientId:
    Type: String
    Description: "Google Client ID"
  GoogleClientSecret:
    Type: String
    Description: "Google Client Secret"
  GoogleRedirectUri:
    Type: String
    Description: "Google Redirect URI"

Globals:
  Function:
    Timeout: 60

Resources:
  AppointmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      OnDemandThroughput:
        MaxReadRequestUnits: 10
        MaxWriteRequestUnits: 10
  
  WorkingScheduleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: DoctorId
          AttributeType: S
        - AttributeName: Date
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      OnDemandThroughput:
        MaxReadRequestUnits: 10
        MaxWriteRequestUnits: 10
      GlobalSecondaryIndexes:
        - IndexName: DoctorIdAndDateIndex
          KeySchema:
            - AttributeName: DoctorId
              KeyType: HASH
            - AttributeName: Date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  
  PatientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: UserId
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      OnDemandThroughput:
        MaxReadRequestUnits: 10
        MaxWriteRequestUnits: 10
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: UserId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  
  DoctorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      OnDemandThroughput:
        MaxReadRequestUnits: 10
        MaxWriteRequestUnits: 10

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      OnDemandThroughput:
        MaxReadRequestUnits: 10
        MaxWriteRequestUnits: 10

  UserIndexTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      OnDemandThroughput:
        MaxReadRequestUnits: 10
        MaxWriteRequestUnits: 10
  
  AppointmentIndexTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: 'PAY_PER_REQUEST'
      OnDemandThroughput:
        MaxReadRequestUnits: 10
        MaxWriteRequestUnits: 10
  
  DistributedLockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ExpiredAt
        Enabled: true

  BackendApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName

  ExpressFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Policies:
        - AmazonDynamoDBFullAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action: 'bedrock:InvokeAgent'
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action:
                - 'ses:SendEmail'
                - 'ses:SendRawEmail'
              Resource: !Ref SesArn
      Environment:
        Variables:
          APPOINTMENT_TABLE_NAME: !Ref AppointmentsTable
          DOCTOR_TABLE_NAME: !Ref DoctorsTable
          USER_TABLE_NAME: !Ref UsersTable
          USER_INDEX_TABLE_NAME: !Ref UserIndexTable
          PATIENTS_TABLE_NAME: !Ref PatientsTable
          WORKING_SCHEDULE_TABLE_NAME: !Ref WorkingScheduleTable
          API_STAGE_NAME: !Ref StageName
          BEDROCK_AGENT_ID_UNREGISTERED: !Ref BedrockAgentIdUnregisteredUser
          BEDROCK_AGENT_ALIAS_UNREGISTERED: !Ref BedrockAgentAliasUnregisteredUser
          BEDROCK_AGENT_ID_REGISTERED: !Ref BedrockAgentIdRegisteredUser
          BEDROCK_AGENT_ALIAS_REGISTERED: !Ref BedrockAgentAliasRegisteredUser
          APPOINTMENT_INDEX_TABLE_NAME: !Ref AppointmentIndexTable
          SES_ARN: !Ref SesArn
          WEB_BASE_URL: !Ref WebBaseUrl
          DISTRIBUTED_LOCK_TABLE_NAME: !Ref DistributedLockTable
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          GOOGLE_REDIRECT_URI: !Ref GoogleRedirectUri
      Events:
        Root:
          Type: HttpApi
          Properties:
            ApiId: !Ref BackendApi
            Path: /
            Method: ANY
        Petstore:
          Type: HttpApi
          Properties:
            ApiId: !Ref BackendApi
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: v1
      DockerContext: ./app
      Dockerfile: Dockerfile

Outputs:
  ExpressApi:
    Description: "API Gateway endpoint URL for Prod stage for Express function"
    Value: !Sub "https://${BackendApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/"
