openapi: 3.0.0
info:
  title: GP Appointment Management API
  version: 1.0.0
  description: API to manage appointments with General Practitioners (GPs)

paths:
  #
  # doctor info api
  #
  /doctors:
    get:
      summary: List all doctors
      operationId: listDoctors
      description: list doctors. It can be filtered by workplace.
      parameters:
        - name: firstname
          in: query
          description: First name of the doctor
          schema:
            type: string
        - name: lastname
          in: query
          description: Last name of the doctor
          schema:
            type: string 
        - name: workplace
          in: query
          description: Name of the workplace to filter doctors by
          schema:
            type: string
      responses:
        '200':
          description: A list of doctors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Doctor'
  /schedules:
    get:
      summary: Get a list of working schedules
      operationId: listSchedules
      description: Retrieve a list of appointment timeslot filtered by doctor ID and date range. you cannot book the schedule whose Status is occupied
      parameters:
        - in: query
          name: doctorId
          schema:
            type: string
          required: true
          description: ID of the doctor to filter schedules.
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            format: date
          description: Start date to filter schedules.
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            format: date
          description: End date to filter schedules.
      responses:
        '200':
          description: A list of working schedules.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
        '500':
          description: Server error.
  #
  # Clinic
  #
  /clinics:
    get:
      summary: List all clinics
      operationId: listClinics
      description: list clinics, including name and address
      responses:
        '200':
          description: A list of clinics
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    workplace:
                      type: string
                      description: Name of the clinic
                    address:
                      type: string
                      description: Address of the clinic

components:
  schemas:
    Doctor:
      type: object
      properties:
        DoctorId:
          type: string
          description: Unique identifier for the doctor. DoctorId.
        DoctorFirstName:
          type: string
          description: First name of the Doctor. DoctorFirstName.
        DoctorLastName:
          type: string
          description: Last name of the Doctor. DoctorLastName.
        DoctorSpecialty:
          type: string
          description: Medical specialty of the Doctor. DoctorSpecialty.
        DoctorPhone:
          type: string
          description: Contact phone number of the Doctor. DoctorPhone.
        DocotrEmail:
          type: string
          description: Email address of the Doctor. DoctorEmail.
        DoctorWorkplace:
          type: string
          description: Workplace. DoctorWorkplace.
        DoctorAddress:
          type: string
          description: Address of the workplace. DoctorAddress.
    Schedule:
      type: object
      properties:
        Id:
          type: string
          description: it is ScheduleId
        DoctorId:
          type: string
          description: id of the doctor
        DoctorName:
          type: string
          description: name of the doctor
        Date:
          type: string
          format: date
          description: timeslot date
        StartTime:
          type: string
          format: time
          description: timeslot start time
        EndTime:
          type: string
          format: time
          description: timeslot end time
        Status:
          type: string
          description: status of this timeslot. you cannot book occupied timeslot
          enum:
            - available
            - occupied