openapi: 3.0.0
info:
  title: GP Appointment Management API
  version: 1.0.0
  description: API to manage appointments with General Practitioners (GPs)

paths:
  /appointments/{appointmentId}/reschedule:
    post:
      summary: Reschedule an appointment
      description: Reschedule an existing appointment to a new schedule for user.
      operationId: rescheduleAppointment
      parameters:
        - in: path
          name: appointmentId
          description: The ID of the appointment to be rescheduled.
          required: true
          schema:
            type: string
        - in: query
          name: x_access_token
          schema:
            type: string
          required: true
          description: x_access_token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ScheduleId:
                  type: string
                  description: The new schedule ID for the appointment.
              required:
                - ScheduleId
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '500':
          description: Internal server error
  /user/appointments:
    get:
      summary: List all appointments of current user.
      description: List all appointments of current user.
      operationId: listAppointments
      parameters:
        - in: query
          name: x_access_token
          schema:
            type: string
          required: true
          description: x_access_token
      responses:
        '200':
          description: A list of appointments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
    post:
      summary: Create a new appointment for the current user
      description: Create a new appointment for the current user
      operationId: createUserAppointment
      parameters:
        - in: query
          name: x_access_token
          schema:
            type: string
          required: true
          description: x_access_token
      requestBody:
        description: Appointment object that needs to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ScheduleId
                - FirstName
                - LastName
                - DateOfBirth
              properties:
                FirstName:
                  type: string
                  description: First name of the User. UserFirstName.
                LastName:
                  type: string
                  description: Last name of the User. UserLastName.
                DateOfBirth:
                  type: string
                  format: date
                  description: date of birth of the User. UserDateOfBirth.
                ScheduleId:
                  type: string
                  description: Unique identifier for the booking timeslot
                Reason:
                  type: string
                  description: Reason for the appointment
                Email:
                  type: string
                  description: Email address of the User. UserEmail.
                PhoneNumber:
                  type: string
                  description: Phone number of the User. UserPhoneNumber.
      responses:
        '201':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid input
  /appointments/{appointmentId}/cancel:
    post:
      summary: Cancel an appointment
      operationId: cancelAppointment
      description: Cancel an existing appointment for user.
      parameters:
        - in: query
          name: x_access_token
          schema:
            type: string
          required: true
          description: x_access_token
        - name: appointmentId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the appointment to cancel
      responses:
        '200':
          description: Appointment cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '404':
          description: Appointment not found
        '500':
          description: Internal server error

components:
  schemas:
    Appointment:
      type: object
      properties:
        Id:
          type: string
          description: Unique identifier for the appointment
        FirstName:
          type: string
          description: First name of the User. UserFirstName.
        LastName:
          type: string
          description: Last name of the User. UserLastName.
        DateOfBirth:
          type: string
          format: date
          description: date of birth of the User. UserDateOfBirth.
        BookingReference:
          type: string
          description: booking reference
        ScheduleId:
          type: string
          description: Unique identifier for the booking timeslot
        DoctorId:
          type: string
          description: Unique identifier for the doctor
        DoctorName:
          type: string
          description: Name of the General Practitioner
        Date:
          type: string
          format: date
          description: Date of the appointment
        StartTime:
          type: string
          format: time
          description: Start time of the appointment
        EndTime:
          type: string
          format: time
          description: End time of the appointment
        Reason:
          type: string
          description: Reason for the appointment
        Status:
          type: string
          enum:
            - active
            - cancelled
            - completed
          description: Status of the appointment
        Email:
          type: string
          description: Email address of the User. UserEmail.
        PhoneNumber:
          type: string
          description: Phone number of the User. UserPhoneNumber.