AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BedrockAgentForUnregisteredUserResourceName:
    Type: String
    Description: The ARN of the resource that will have InvokeFunction permission.
  BedrockAgentForRegisteredUserResourceName:
    Type: String
    Description: The ARN of the resource that will have InvokeFunction permission.

Resources:
  GPBoookingAIAgentLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler  # Adjust to your handler
      Runtime: python3.12
      CodeUri: ./src  # Adjust to your code location
      MemorySize: 128
      Timeout: 10
  
  LambdaPermission1:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt GPBoookingAIAgentLambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      SourceArn: !Sub "${BedrockAgentForUnregisteredUserResourceName}"
      Principal: "bedrock.amazonaws.com"

  LambdaPermission2:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !GetAtt GPBoookingAIAgentLambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      SourceArn: !Sub "${BedrockAgentForRegisteredUserResourceName}"
      Principal: "bedrock.amazonaws.com"

Outputs:
  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref GPBoookingAIAgentLambdaFunction
