openapi: 3.0.0
info:
  title: GP Appointment Management API
  version: 1.0.0
  description: API to manage appointments with General Practitioners (GPs)

paths:
  /appointment:
    get:
      summary: Get appointment by booking reference
      description: Retrieve an appointment using the booking reference, last name, and date of birth 
      parameters:
        - in: query
          name: reference
          description: The booking reference of the appointment.
          required: true
          schema:
            type: string
        - in: query
          name: lastname
          description: The last name of the person who booked the appointment.
          required: true
          schema:
            type: string
        - in: query
          name: dob
          description: The date of birth of the person who booked the appointment.
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '500':
          description: Internal server error
  /appointments:
    post:
      summary: Create a new appointment
      description: Create a new appointment for user.
      operationId: createAppointmentForUnregisteredUser
      requestBody:
        description: Appointment object that needs to be added
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - ScheduleId
                - FirstName
                - LastName
                - DateOfBirth
                - PhoneNumber
                - Email
              properties:
                FirstName:
                  type: string
                  description: First name of the User. UserFirstName.
                LastName:
                  type: string
                  description: Last name of the User. UserLastName.
                DateOfBirth:
                  type: string
                  format: date
                  description: date of birth of the User. UserDateOfBirth.
                ScheduleId:
                  type: string
                  description: Unique identifier for the booking timeslot
                Reason:
                  type: string
                  description: Reason for the appointment
                Email:
                  type: string
                  description: Email address of the User. UserEmail.
                PhoneNumber:
                  type: string
                  description: Phone number of the User. UserPhoneNumber.
      responses:
        '201':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid input

  /appointments/reschedule:
    post:
      summary: Reschedule an appointment
      description: Reschedule an existing appointment to a new schedule for user.
      operationId: rescheduleAppointmentByBookingReference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                BookingReference:
                  type: string
                  description: The booking reference of the appointment
                LastName:
                  type: string
                  description: The last name of the person who booked the appointment
                DateOfBirth:
                  type: string
                  format: date
                  description: The date of birth of the person who booked the appointment
                ScheduleId:
                  type: string
                  description: The new schedule ID for rescheduling the appointment
              required:
                - BookingReference
                - LastName
                - DateOfBirth
                - ScheduleId
      responses:
        '200':
          description: Appointment rescheduled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Appointment linked to a user, login required to reschedule
        '404':
          description: Appointment not found
        '500':
          description: Internal server error
  /appointments/cancel:
    post:
      summary: Cancel an appointment
      operationId: cancelAppointmentByBookingReference
      description: Cancel an existing appointment for user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                BookingReference:
                  type: string
                  description: The booking reference of the appointment
                LastName:
                  type: string
                  description: The last name of the person who booked the appointment
                DateOfBirth:
                  type: string
                  format: date
                  description: The date of birth of the person who booked the appointment
              required:
                - BookingReference
                - LastName
                - DateOfBirth
      responses:
        '200':
          description: Appointment cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Appointment linked to a user, login required to cancel
        '403':
          description: Forbidden
        '500':
          description: Internal server error
  
components:
  schemas:
    Appointment:
      type: object
      properties:
        Id:
          type: string
          description: Unique identifier for the appointment
        FirstName:
          type: string
          description: First name of the patient. UserFirstName.
        LastName:
          type: string
          description: Last name of the patient. UserLastName.
        DateOfBirth:
          type: string
          format: date
          description: date of birth of the patient. UserDateOfBirth.
        BookingReference:
          type: string
          description: booking reference
        ScheduleId:
          type: string
          description: Unique identifier for the booking timeslot
        DoctorId:
          type: string
          description: Unique identifier for the doctor
        DoctorName:
          type: string
          description: Name of the General Practitioner
        Date:
          type: string
          format: date
          description: Date of the appointment
        StartTime:
          type: string
          format: time
          description: Start time of the appointment
        EndTime:
          type: string
          format: time
          description: End time of the appointment
        Reason:
          type: string
          description: Reason for the appointment
        Status:
          type: string
          enum:
            - active
            - cancelled
            - completed
          description: Status of the appointment
        Email:
          type: string
          description: Email address of the User. UserEmail.
        PhoneNumber:
          type: string
          description: Phone number of the User. UserPhoneNumber.