name: test backend service layer

on:
  push:
    branches:
      - github-action
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run start local env
        run: docker compose up -d --build

      - name: Run api tests
        run: docker compose exec backend npm run test

      - name: Print the logs
        run: docker compose logs backend

      
      

      
