name: test backend service layer

on:
  push:
    branches:
      - github-action
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run start local env
        run: docker compose up -d --build
      
      - name: Init database
        run: |
          until sh ./backend/init-db.sh; do
            echo "Init-db script failed. Retrying in 5 seconds..."
            sleep 5
          done

      - name: Run api tests
        run: sh ./backend/test/api-test.sh

      - name: Print the logs
        run: docker compose logs backend

      
      

      
