name: test backend service layer

on:
  push:
    branches:
      - github-action
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run unit test
        run: docker run --rm -v ./backend/app:/app -w /app public.ecr.aws/sam/build-nodejs18.x sh -c "npm install && npm test"       

      
      

      
